### ISSUE TITLE
we support!

### ISSUE THREAD

**Issue by ghost** [samuelGrahame/MonsajemDatabaseForBridge#1]
thanks to use our products
if you have any idea about our products just say **;)**  
we do or tell our logic
Monsajem_incs

**Comment by samuelGrahame** [comment]
hey how are you, I wanted to make something similar regarding the js server project you made

I want to mix below what I made, with this: 

https://github.com/samuelGrahame/ProjectWeb
https://github.com/samuelGrahame/NarNar

with this

https://github.com/samuelGrahame/ExpressCraft

i really like your idea of the js logic from the server side.

The only issue i have is because all js is dynamic, it could cause issues as you can't release js file with sha256 and put on cdn.

if you had a way of getting it to generate all logic.

for instance below code:

system modifier is used for both client and server objects.
client is used for the client.
server is used in the server side, but a server request stub is generated on the client aka

```csharp

system class Customer
{
	public int Id;
	public string LastName;
	public string FirstName;		
}

server Customer Get()
{
	return new Customer()
	{
		Id = 1,
		LastName = "LastName",
		FirstName = "FirstName"	
	};
}

client static void Main()
{
	var cust = Get();

	Console.WriteLine($"{cust.LastName} {cust.FirstName}");
}

```

**Comment by ghost** [comment]
hi bro
in fact i'm very busy, we need money for real projects, but it's not mean idon't your requests
i saw ExpressCraft online test, that's nice, grate work
but i don't understand what you say, which project do you mean?
bridge.net? or monsajem http service?

**Comment by samuelGrahame** [comment]
hey, okay, i was meaning a project i was going to make is very simular, where you can code one project with for both client and server.

**Comment by ghost** [comment]
do you learn about node js or Apache cordova?
they can run your code in server and i recommended Apache cordova, so learn about that
you may want to write a project to run in any platform, write one project and run on any platform, on this hybrid is best option.

but i think you want something more, if you want write a website project then you have very powerful options
php, asp, and so on...
today Microsoft working on **blazor**, did you saw that? you must, that is awesome believe me
blazor can run your native codes in browsers, so you can write your code and run in any platform or run as website

i hope this can help

**Comment by samuelGrahame** [comment]
Blazor will take around 5 years to be used in production. it is 20x slow then raw csharp and does not have access to dom elements or api.

well I can just write a web app in asp.net core - that way i can put it on Apache or IIS - .net core can compile on linux / mac / win

**Comment by samuelGrahame** [comment]
did you have a look at this: 

https://github.com/samuelGrahame/ProjectWeb

it a way of writing c# like php - for web development I was just playing around. works alright. supports include etc like php.

**Comment by ghost** [comment]
ok i think i understand
in fact we leave asp.net, did you see our hybrid system : [Monsajem Website Service](https://github.com/samuelGrahame/Monsajem_WebsiteService)

we don't like write c# codes in html file
but in that system you can controll html file from server which now can write c# codes
ok let me tell example based ProjectWeb
## this is WebProject :
```csharp
<?cs
var servername = "localhost";
var username = "username";
var password = "password";
var dbname = "myDB";

var conn = new Mysql(servername, username, password, dbname);

if (!conn) {
    Echo("Connection failed: " + conn.Error());
	return;
}

var results = conn.Query("SELECT id, firstname, lastname FROM MyGuests");

if (results.NumberRows > 0) {
    Echo("<table><tr><th>ID</th><th>Name</th></tr>");
    // output data of each row
	  MysqlRow row;
    while(row = results.FetchAssoc()) {
        Echo("<tr><td>" + row["id"] + "</td><td>" + row["firstname"] + " " + row["lastname"] + "</td></tr>");
    }
    Echo("</table>");
} else {
    Echo("0 results");
}
conn.Close();
?>
```

## this is monsajem web service:

```csharp

var servername = "localhost";
var username = "username";
var password = "password";
var dbname = "myDB";

var conn = new Mysql(servername, username, password, dbname);

if (!conn) {
    js.Alert("Connection failed: " + conn.Error());
	return;
}

var results = conn.Query("SELECT id, firstname, lastname FROM MyGuests");

if (results.NumberRows > 0) {
    var ResultHtml ="<table><tr><th>ID</th><th>Name</th></tr>";
    // output data of each row
	  MysqlRow row;
    while(row = results.FetchAssoc()) {
        ResultHtml+= "<tr><td>" + row["id"] + "</td><td>" + row["firstname"] + " " + row["lastname"] + "</td></tr>";
    }
    ResultHtml+="</table>";

js.Document.Append(ResultHtml);

} else {
     js.Alert("0 results");
}
conn.Close();
```

**Comment by ghost** [comment]
the monsajem web service is standard for .net standard so don't worry about linux and windows

**Comment by samuelGrahame** [comment]
yeah i cloned the project before. but the problem with the current solution - which is what i said first.
because you write script - it is very bad and mostly likely gets blocked by a lot of extensions. as it is dynamic js

**Comment by ghost** [comment]
ok if you push a sample project (not codes only) i work on errors and fix that
that have a little bugs if you don't know how use
i don't put extra exceptions for run faster, but now i think this may important for easy debug

just push a sample on github then i 100% fix this bug very soon, don't worry

**Comment by samuelGrahame** [comment]
did you have a chance to look at this github project

https://github.com/samuelGrahame/NarNar

its just an idea, but i would imagine a easy way for debugging and test would be to generate client and server side code.

**Comment by ghost** [comment]
i saw that but i can't debug your codes, i don't understand that at all
your projects really need a sample test for someone like me
now we must work on our product, we really need money for our works, so i maybe don't online about 2 next mounts

**Comment by ghost** [comment]
I saw the issue again, in past i didn't know what is cdn but now i understand what u say
Mosajem http service cant handle cdn for javascripts
In fact cant for any thing
This framework adapted for hybrid apps, not for websites (not today)
But i will find a way for that, now you maybe can fix this as hand fix but i don't recomamd to use it for website because of security issues, i will fix but don't expect me a lot
Mosajem is startup and i have really big problems and chalengs
I will focuse on cdn and others at about 5 next mounts

**Comment by samuelGrahame** [comment]
don't worry, yeah i understand you can use this framework on other systems like android or winforms etc. don't worry about fixing it, i was just telling you my opinions about the framework. I wanted to express that I liked what you are doing. good idea - you focus on your business - which should be the main goal.

I also too have to focus on my day job - wish i could send all my time on inventing open source stuff. but need to pay the bills

**Comment by ghost** [comment]
Based on new features in our product the CDN must not be in servers, that is exactly right on client side
but its just about files not logics or dynamic javascripts, because security issues,
this feature will making on next mount based our needs

**Comment by ghost** [comment]
Oh sorry that isn't cdn, that is cash files on client
